### ISSUE TITLE
birdc show route doesn't show 'filtered'

### ISSUE THREAD

**Issue by ezrizhu** [natesales/zsh-bird-completions#2]
when doing `birdc show route` then press tab, there is no `filtered`, which would show all filtered routes.
![image](https://not-a.link/7qBm5Aj.png)

**Comment by natesales** [comment]
Thanks! Fixed in https://github.com/natesales/zsh-bird-completions/commit/9da23c2f8df98429d2639f6023927c0165573283

**Comment by natesales** [comment]
Thanks! Fixed in https://github.com/natesales/zsh-bird-completions/commit/9da23c2f8df98429d2639f6023927c0165573283
